version: "3"
services:
  database:
    image: mysql
    ports:
      - "3307:3306"
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: UniversityManagementSystem_DB
  spring-app:
    image: spring-mysql-docker
    ports:
      - "8081:8081"
    container_name: spring-mysql-docker
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
